In [23]:
lst=list(range(50, 61))
print(lst)

[50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60]


In [24]:
import numpy as np

b = np.arange(50, 61)
print(b)


[50 51 52 53 54 55 56 57 58 59 60]


In [25]:
d = list(range(50, 61, 2))
print(d)

[50, 52, 54, 56, 58, 60]


In [26]:


b = np.arange(50, 61, 2)
print(b)

[50 52 54 56 58 60]


In [27]:

b = np.arange(3, 100, 3)
print(b)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [28]:


b = np.array([43, 62, 32])
print(b)

[43 62 32]


In [33]:
import numpy as np

array = np.array([[0, 1, 2], [1, 2, 3]])
print(array)

[[0 1 2]
 [1 2 3]]


In [34]:
array = np.zeros((2,4))
print(array)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [37]:
array = np.ones((4,3))
print(array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [40]:
array = np.eye(5)
print(array)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [44]:
array = np.arange(0,10,3)
print(array)

[0 3 6 9]


In [52]:
array = np.random.randint(0,100,(3,3))
print(array)

[[43 10 57]
 [21 79 36]
 [64 86 89]]


In [59]:
lst = list(([0, 1, 2],[1, 2, 3]))
print(lst)

[[0, 1, 2], [1, 2, 3]]


In [60]:
matrix = list([
    [0, 1, 2],
    [1, 2, 3]
])

print(matrix)

[[0, 1, 2], [1, 2, 3]]
